# Private mapping of our hosts to shareable hardware profiles (not part of profiles).
phone7: samsung-a57-sm-a576u-exynos1680-android16
phone8: samsung-a57-sm-a576u-exynos1680-android16
miryam: intel-kbl-i5-7200u-hd620-linux
qodesh: nvidia-g84-8600gt-athlon2x2-win10
